FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=vulnerable_password
ENV MYSQL_DATABASE=wanderlust_db

COPY init.sql /docker-entrypoint-initdb.d/

# To ensure the script is executable
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql