apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wanderlust
  template:
    metadata:
      labels:
        app: wanderlust
    spec:
      containers:
      - name: server
        image: ivan-tresoldi/wanderlust:latest
        ports:
        - containerPort: 9000
