apiVersion: v1
kind: Service
metadata:
  name: wanderlust-service
  namespace: wanderlust
spec:
  type: LoadBalancer
  selector:
    app: wanderlust
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000  # Exposing the client application
